import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import Nav from "@/app/components/Nav";
import { TRPCReactProvider } from "@/trpc/react";
import Provider from "./components/Provider";
import { getServerSession } from "next-auth";

export const metadata = {
  title: "Media Bouderga",
  description: "Generated by Abdel-samade Bouderga",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <TRPCReactProvider>
            <Nav />
            {children}
          </TRPCReactProvider>
        </Provider>
      </body>
    </html>
  );
}
