import "@/styles/globals.css";
import Nav from "@/app/components/Nav";
import { TRPCReactProvider } from "@/trpc/react";
import Provider from "@/app/components/Provider";
import type { ReactNode } from "react";

import ReactQueryProvider from "./components/ReactQueryProvider";

export const metadata = {
  title: "Media Bouderga",
  description: "Generated by Abdel-samade Bouderga",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <Provider>
          <ReactQueryProvider>
            <TRPCReactProvider>
              <Nav />
              {children}
            </TRPCReactProvider>
          </ReactQueryProvider>
        </Provider>
      </body>
    </html>
  );
}
